env:
  # GitHub username
  - secure: "/wI5JrITZlXP2/yVahUahVcEgPVHphFKY1IKtusA3BAe/NDwkIYmNZ7e"

  # GitHub password
  - secure: "IwJ/RuETZlVYjzY3y7h5ZKeyi9CI3W0odjAnG1PFjFjPDC0NEk++fPCeDfHVrNBl"

before_script:
  - cd behat
  # Instead of composer install, we save time by getting
  # a gzipped file with the vendor and bin directories.
  - tar zxf behat-vendor.tar.gz
  - cp behat.local.yml.example behat.local.yml

script:
  - ./bin/behat --tags=~wip
